name: edit_detect
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ipykernel=6.29.3
  - ipython=8.24.0
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.42
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.10.14
  - python_abi=3.10
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
    - accelerate==0.30.1
    - bz2file==0.98
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - contourpy==1.2.1
    - cycler==0.12.1
    # - diffusers==0.28.0.dev0
    - filelock==3.14.0
    - fonttools==4.51.0
    - fsspec==2024.3.1
    - huggingface-hub==0.23.0
    - idna==3.7
    - importlib-metadata==7.1.0
    - jinja2==3.1.4
    - kiwisolver==1.4.5
    - markupsafe==2.1.5
    - matplotlib==3.9.0
    - mpmath==1.3.0
    - networkx==3.3
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - opencv-python==4.9.0.80
    - pandas==2.2.2
    - pillow==10.3.0
    - psutil==5.9.8
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - regex==2024.5.10
    - requests==2.31.0
    - safetensors==0.4.3
    - scipy==1.13.0
    - sympy==1.12
    - tokenizers==0.19.1
    - torch==2.3.0
    - torchaudio==2.3.0
    - torchvision==0.18.0
    - tqdm==4.66.4
    - transformers==4.40.2
    - triton==2.3.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - zipp==3.18.1
